apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-metrics
  labels:
    metrics-infra: hawkular-cassandra
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /home/data/persistent5
    server: master.example.com
  persistentVolumeReclaimPolicy: Recycle
